# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fc_estbth_2SLS_TS <- function(Me, Mpi, tauseq, N, T, q, p, y0, Z, X, W1, W2, secA1, secA2, rhoest_hc, Best_hc, phiest_hc, etaest_hc, thetaest_hc, rho_ini) {
    .Call(`_QuantileDSPM_fc_estbth_2SLS_TS`, Me, Mpi, tauseq, N, T, q, p, y0, Z, X, W1, W2, secA1, secA2, rhoest_hc, Best_hc, phiest_hc, etaest_hc, thetaest_hc, rho_ini)
}

fc_estBnum_2SLS_TS <- function(Bnum, dimALL, Me, Mpi, tauseq, N, T, q, p, y0, Z, X, W1, W2, secA1, secA2, rhoest_hc, Best_hc, phiest_hc, etaest_hc, thetaest_hc, rho_ini) {
    .Call(`_QuantileDSPM_fc_estBnum_2SLS_TS`, Bnum, dimALL, Me, Mpi, tauseq, N, T, q, p, y0, Z, X, W1, W2, secA1, secA2, rhoest_hc, Best_hc, phiest_hc, etaest_hc, thetaest_hc, rho_ini)
}

fc_asmat <- function(vec1, nrow, ncol) {
    .Call(`_QuantileDSPM_fc_asmat`, vec1, nrow, ncol)
}

fc_asvec <- function(mat1) {
    .Call(`_QuantileDSPM_fc_asvec`, mat1)
}

fc_iota <- function(n) {
    .Call(`_QuantileDSPM_fc_iota`, n)
}

fc_I <- function(n) {
    .Call(`_QuantileDSPM_fc_I`, n)
}

fc_B <- function(rho, N, W2) {
    .Call(`_QuantileDSPM_fc_B`, rho, N, W2)
}

fc_MatrixMultip <- function(M1, M2) {
    .Call(`_QuantileDSPM_fc_MatrixMultip`, M1, M2)
}

fc_phitilde_2SLS <- function(wrD, wrH, wrH_pred) {
    .Call(`_QuantileDSPM_fc_phitilde_2SLS`, wrD, wrH, wrH_pred)
}

fc_etaest <- function(phiest, Y, Zbreve) {
    .Call(`_QuantileDSPM_fc_etaest`, phiest, Y, Zbreve)
}

fc_Vtilde <- function(etatilde, N, T) {
    .Call(`_QuantileDSPM_fc_Vtilde`, etatilde, N, T)
}

fc_secA1 <- function(W2, N) {
    .Call(`_QuantileDSPM_fc_secA1`, W2, N)
}

fc_Lambda1lambda1 <- function(Vtilde, N, T, W2, secA1, secA2) {
    .Call(`_QuantileDSPM_fc_Lambda1lambda1`, Vtilde, N, T, W2, secA1, secA2)
}

fc_Sigmavarepsilonest <- function(Best, Vtilde, N, T) {
    .Call(`_QuantileDSPM_fc_Sigmavarepsilonest`, Best, Vtilde, N, T)
}

fc_Sigmagest <- function(Sigma_varepsilonest, secA1, secA2, N) {
    .Call(`_QuantileDSPM_fc_Sigmagest`, Sigma_varepsilonest, secA1, secA2, N)
}

fc_kappacheck <- function(Lambda1, lambda1) {
    .Call(`_QuantileDSPM_fc_kappacheck`, Lambda1, lambda1)
}

fc_phihat <- function(etatilde, Bhat, Sigma_varepsilonhat, N, T, Y, Zbreve) {
    .Call(`_QuantileDSPM_fc_phihat`, etatilde, Bhat, Sigma_varepsilonhat, N, T, Y, Zbreve)
}

IQR_rcpp <- function(x) {
    .Call(`_QuantileDSPM_IQR_rcpp`, x)
}

dnorm_rcpp <- function(x) {
    .Call(`_QuantileDSPM_dnorm_rcpp`, x)
}

fc_Xihattauseq <- function(tauseq, N, thetahat, Xwith1, varphihat) {
    .Call(`_QuantileDSPM_fc_Xihattauseq`, tauseq, N, thetahat, Xwith1, varphihat)
}

fc_ASDvarphihat <- function(tauseq, N, p, thetahat, X, varphihat) {
    .Call(`_QuantileDSPM_fc_ASDvarphihat`, tauseq, N, p, thetahat, X, varphihat)
}

f_Ystarmat_Generation_TS <- function(N, T, q, y0, rhohat, phihat, thetahat, varepsilonstar, Zarray, W1, W2) {
    .Call(`_QuantileDSPM_f_Ystarmat_Generation_TS`, N, T, q, y0, rhohat, phihat, thetahat, varepsilonstar, Zarray, W1, W2)
}

fc_varepsilonstar_TS <- function(estar, N, T, Bhat, etahat) {
    .Call(`_QuantileDSPM_fc_varepsilonstar_TS`, estar, N, T, Bhat, etahat)
}

noZ_fc_estbth_2SLS_TS <- function(Me, Mpi, tauseq, N, T, q, p, y0, X, W1, W2, secA1, secA2, rhoest_hc, Best_hc, phiest_hc, etaest_hc, thetaest_hc, rho_ini) {
    .Call(`_QuantileDSPM_noZ_fc_estbth_2SLS_TS`, Me, Mpi, tauseq, N, T, q, p, y0, X, W1, W2, secA1, secA2, rhoest_hc, Best_hc, phiest_hc, etaest_hc, thetaest_hc, rho_ini)
}

noZ_fc_estBnum_2SLS_TS <- function(Bnum, dimALL, Me, Mpi, tauseq, N, T, q, p, y0, X, W1, W2, secA1, secA2, rhoest_hc, Best_hc, phiest_hc, etaest_hc, thetaest_hc, rho_ini) {
    .Call(`_QuantileDSPM_noZ_fc_estBnum_2SLS_TS`, Bnum, dimALL, Me, Mpi, tauseq, N, T, q, p, y0, X, W1, W2, secA1, secA2, rhoest_hc, Best_hc, phiest_hc, etaest_hc, thetaest_hc, rho_ini)
}

noZ_fc_asmat <- function(vec1, nrow, ncol) {
    .Call(`_QuantileDSPM_noZ_fc_asmat`, vec1, nrow, ncol)
}

noZ_fc_asvec <- function(mat1) {
    .Call(`_QuantileDSPM_noZ_fc_asvec`, mat1)
}

noZ_fc_iota <- function(n) {
    .Call(`_QuantileDSPM_noZ_fc_iota`, n)
}

noZ_fc_I <- function(n) {
    .Call(`_QuantileDSPM_noZ_fc_I`, n)
}

noZ_fc_B <- function(rho, N, W2) {
    .Call(`_QuantileDSPM_noZ_fc_B`, rho, N, W2)
}

noZ_fc_MatrixMultip <- function(M1, M2) {
    .Call(`_QuantileDSPM_noZ_fc_MatrixMultip`, M1, M2)
}

noZ_fc_phitilde_2SLS <- function(wrD, wrH, wrH_pred) {
    .Call(`_QuantileDSPM_noZ_fc_phitilde_2SLS`, wrD, wrH, wrH_pred)
}

noZ_fc_etaest <- function(phiest, Y, Zbreve) {
    .Call(`_QuantileDSPM_noZ_fc_etaest`, phiest, Y, Zbreve)
}

noZ_fc_Vtilde <- function(etatilde, N, T) {
    .Call(`_QuantileDSPM_noZ_fc_Vtilde`, etatilde, N, T)
}

noZ_fc_secA1 <- function(W2, N) {
    .Call(`_QuantileDSPM_noZ_fc_secA1`, W2, N)
}

noZ_fc_Lambda1lambda1 <- function(Vtilde, N, T, W2, secA1, secA2) {
    .Call(`_QuantileDSPM_noZ_fc_Lambda1lambda1`, Vtilde, N, T, W2, secA1, secA2)
}

noZ_fc_Sigmavarepsilonest <- function(Best, Vtilde, N, T) {
    .Call(`_QuantileDSPM_noZ_fc_Sigmavarepsilonest`, Best, Vtilde, N, T)
}

noZ_fc_Sigmagest <- function(Sigma_varepsilonest, secA1, secA2, N) {
    .Call(`_QuantileDSPM_noZ_fc_Sigmagest`, Sigma_varepsilonest, secA1, secA2, N)
}

noZ_fc_kappacheck <- function(Lambda1, lambda1) {
    .Call(`_QuantileDSPM_noZ_fc_kappacheck`, Lambda1, lambda1)
}

noZ_fc_phihat <- function(etatilde, Bhat, Sigma_varepsilonhat, N, T, Y, Zbreve) {
    .Call(`_QuantileDSPM_noZ_fc_phihat`, etatilde, Bhat, Sigma_varepsilonhat, N, T, Y, Zbreve)
}

noZ_IQR_rcpp <- function(x) {
    .Call(`_QuantileDSPM_noZ_IQR_rcpp`, x)
}

noZ_dnorm_rcpp <- function(x) {
    .Call(`_QuantileDSPM_noZ_dnorm_rcpp`, x)
}

noZ_fc_Xihattauseq <- function(tauseq, N, thetahat, Xwith1, varphihat) {
    .Call(`_QuantileDSPM_noZ_fc_Xihattauseq`, tauseq, N, thetahat, Xwith1, varphihat)
}

noZ_fc_ASDvarphihat <- function(tauseq, N, p, thetahat, X, varphihat) {
    .Call(`_QuantileDSPM_noZ_fc_ASDvarphihat`, tauseq, N, p, thetahat, X, varphihat)
}

noZ_f_Ystarmat_Generation_TS <- function(N, T, q, y0, rhohat, phihat, thetahat, varepsilonstar, W1, W2) {
    .Call(`_QuantileDSPM_noZ_f_Ystarmat_Generation_TS`, N, T, q, y0, rhohat, phihat, thetahat, varepsilonstar, W1, W2)
}

noZ_fc_varepsilonstar_TS <- function(estar, N, T, Bhat, etahat) {
    .Call(`_QuantileDSPM_noZ_fc_varepsilonstar_TS`, estar, N, T, Bhat, etahat)
}

